services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: vuln_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  web:
    build:
      context: .  # Current directory (project root)
      dockerfile: docker/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - db

volumes:
  mysql_data: