name: DevSecOps Pipeline
on: [push]

jobs:
  build-and-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Add Docker setup step
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      # Updated Docker Compose step
      - name: Build containers
        run: |
          docker compose -f docker/docker-compose.yml build
          
      - name: SAST Scan (Semgrep)
        uses: returntocorp/semgrep-action@v1
        with:
          config: p/owasp-top-ten